# Global Settings
kube_namespace: "fullstack-app"
docker_registry: "172.31.9.239"

# MySQL Configuration
mysql_version: "8.0"
mysql_database_name: "mydb"
mysql_storage_size: "5Gi"
mysql_storage_class: "standard"

# Service Ports
backend_service_port: 8080
frontend_service_port: 80

# Resource Defaults
mysql_cpu_request: "500m"
backend_cpu_request: "1000m"
frontend_cpu_request: "500m"
