apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: fullstackapp
data:
  #SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service.fullstackapp.svc.cluster.local:3306/mydb
  SPRING_PROFILES_ACTIVE: dev
