apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fullstackapp
  labels:
    app: fullstack
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstack
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fullstack
        tier: backend
    spec:
      containers:
        - name: backend
          image: basmaoueslati/fullstackproject:backend-{{ version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
