apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: fullstack
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstack
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fullstack
        tier: backend
    spec:
      containers:
      - name: backend
        image: "basmaoueslati/fullstackproject:backend-{{ version }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: backend-config
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            host: 127.0.0.1
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 5

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            host: 127.0.0.1
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 5
