apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ namespace | default("default") }}
  labels:
    app: fullstack
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: fullstack
    tier: backend
  type: ClusterIP