apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: "{{ kube_namespace }}"
  labels:
    app: fullstack
    tier: backend
spec:
  type: NodePort           
  selector:
    app: fullstack
    tier: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080        

