# kubernetes/1-mysql/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ namespace | default("default") }}
type: Opaque
data:
  root-password: {{ root_password | b64encode }}
  username: {{ db_user | b64encode }}
  password: {{ db_password | b64encode }}