---
- name: Deploy fullstack app to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy MySQL stack
      import_playbook: mysql/deployDB.yaml

    - name: Deploy backend
      kubernetes.core.k8s:
        state: present
        namespace: "{{ kube_namespace }}"
        definition: "{{ lookup('file', 'backend/deployment.yaml') | from_yaml }}"

    - name: Deploy backend service
      kubernetes.core.k8s:
        state: present
        namespace: "{{ kube_namespace }}"
        definition: "{{ lookup('file', 'backend/service.yaml') | from_yaml }}"

    - name: Deploy frontend
      kubernetes.core.k8s:
        state: present
        namespace: "{{ kube_namespace }}"
        definition: "{{ lookup('file', 'frontend/deployment.yaml') | from_yaml }}"

    - name: Deploy frontend service
      kubernetes.core.k8s:
        state: present
        namespace: "{{ kube_namespace }}"
        definition: "{{ lookup('file', 'frontend/service.yaml') | from_yaml }}"
