---
- name: Build and Push Frontend & Backend Docker Images
  hosts: localhost
  connection: local
  vars:
    image_tag: "{{ NEXT_VERSION }}"
    docker_registry: "{{ lookup('env', 'DOCKER_REGISTRY') | default('basmaoueslati') }}"
    frontend_path: "{{ build_context }}/frontend"
    backend_path: "{{ build_context }}/backend_app"
    frontend_image: "{{ docker_registry }}/fullstackproject:frontend-{{ image_tag }}"
    backend_image: "{{ docker_registry }}/fullstackproject:backend-{{ image_tag }}"

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Build and push Frontend image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        source: build
        build:
          path: "{{ frontend_path }}"
          pull: yes
          dockerfile: Dockerfile
        force_source: true
        push: yes
        state: present

    - name: Build and push Backend image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: build
        build:
          path: "{{ backend_path }}"
          pull: yes
          dockerfile: Dockerfile
        force_source: true
        push: yes
        state: present

    - name: Verify Frontend image was pushed
      command: docker pull {{ frontend_image }}

    - name: Verify Backend image was pushed
      command: docker pull {{ backend_image }}
